### ISSUE TITLE
Consider dropping PlotlyJS dependency

### ISSUE THREAD

**Issue by fatteneder** [HoBeZwe/NURBS.jl#11]
From what I can see its only needed for the `PlotlyJS` extensions.

So it should suffice to keep it as a `[weakdeps]`, no?

**Comment by HoBeZwe** [comment]
Hi, in the long run, yes.

But for backward compatibility with older Julia versions, I currently follow [this guide](https://pkgdocs.julialang.org/v1/creating-packages/#Transition-from-normal-dependency-to-extension). 

Accordingly, for Julia versions 1.9+ the entry in [deps] should be ignored.
