### ISSUE TITLE
plotSurface(SNurbs, controlPoints=controlPoints) is not working for a different number of control points in the two parametric directions

### ISSUE THREAD

**Issue by TheoGerostathis** [HoBeZwe/NURBS.jl#4]
Command plotSurface with option controlPoints (e.g. plotSurface(SNurbs, controlPoints=controlPoints)) is not working for a different number of control points in the two parametric directions.  

In file "src/utils/plotting.jl" please replace line 130 with the following:

maxmax, t2 = plotControlPoints(controlPoints[ind,:])

and line 136 with:

maxmax2, t2 = plotControlPoints(controlPoints[:,ind])

**Comment by HoBeZwe** [comment]
Thank you for pointing this out. It is fixed in the newest release.
