### ISSUE TITLE
Logo cut off

### ISSUE THREAD

**Issue by PallHaraldsson** [HoBeZwe/NURBS.jl#6]
Hi,

I noticed the current (and older) loge have most of the N cut off. I was thinking is it intentional, some stylistic chose I don't understand?

It stands for:
"NURBS (non-uniform rational B-spline) basis", and maybe I'm reading too much into it, but the N stands for non[-uniform], so without it would be uniform rational B-spline basis, if that even makes sense. Is it to imply that somehow, that or both can be done?

**Comment by HoBeZwe** [comment]
Hi, 
the N of the logo should actually be fully visible. In my browser it is. Are you maybe viewing it on a smartphone or a special browser?

**Comment by PallHaraldsson** [comment]
No just in Firefox 119 on Linux desktop. I recently switched back from Edge. If I switch back or try, I could let you know, it might be a browser bug in Firefox only.

**Comment by cormullion** [comment]
I think there are issues with the embedded fonts:

<img width="1111" alt="Screenshot 2023-11-17 at 14 40 34" src="https://github.com/HoBeZwe/NURBS.jl/assets/52289/11093907-a372-4383-8916-241db2c5812f">

It might be better to convert text to curves at some stage before saving as SVG.

**Comment by HoBeZwe** [comment]
I've updated the logo. The text is now converted to a curve (thanks for the hint @cormullion !). Hopefully, this fixes the issues with the cut-off N.
